from typing import List
from myUtils.Utils import printResult

"""
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

"""
class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        n, m = len(str1), len(str2)
        l = n + m - 1
        word = [None] * l
        fixed = [False] * l
        
        # 1. Satisfy 'T' constraints (Absolute)
        for i, s in enumerate(str1):
            if s == 'T':
                for j in range(m):
                    char = str2[j]
                    if word[i + j] is not None and word[i + j] != char:
                        return ""
                    word[i + j] = char
                    fixed[i + j] = True
        
        # 2. Fill remaining with 'a' for lexicographical smallest
        for i in range(l):
            if word[i] is None:
                word[i] = 'a'
        
        # Pre-convert for faster slicing and comparison
        target = list(str2)
        
        # 3. Satisfy 'F' constraints greedily from left to right
        for i, s in enumerate(str1):
            if s == 'F':
                # Slicing and comparing is O(m), efficient for n=10^4, m=500
                if word[i : i+m] == target:
                    # Match found! Change the rightmost possible unfixed character.
                    found_k = False
                    for k in range(i + m - 1, i - 1, -1):
                        if not fixed[k]:
                            original_char = word[k]
                            # Try smallest characters that break the match ('b', 'c'...)
                            # We start from 'b' because it was 'a' and str2[k-i] must be 'a'
                            for char_code in range(ord('b'), ord('z') + 1):
                                c = chr(char_code)
                                if c == str2[k - i]:
                                    continue
                                
                                word[k] = c
                                
                                # Check if this change created a new violation for j <= i
                                is_safe = True
                                for j in range(max(0, k - m + 1), i + 1):
                                    if str1[j] == 'F' and word[j : j+m] == target:
                                        is_safe = False
                                        break
                                
                                if is_safe:
                                    found_k = True
                                    break
                            
                            if found_k:
                                break
                            word[k] = original_char # Backtrack if this k didn't work
                    
                    if not found_k:
                        return ""
        
        return "".join(word)
    
obj = Solution()

str1 = "TFTF"
str2 = "ab"
expected = "ababa"
result = obj.generateString(str1, str2)
printResult(result, expected)

str1 = "TFTF"
str2 = "abc"
expected = ""
result = obj.generateString(str1, str2)
printResult(result, expected)

